spring.datasource.url=jdbc:postgresql://dpg-d75plojuibrs73bs6po0-a.singapore-postgres.render.com:5432/db3_5iv0
spring.datasource.username=db3_5iv0_user
spring.datasource.password=XOMWRHGCA9F3jkRCXzhgKSSK9QLnEt4F

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}

server.id=3